name: Add Submodules

on:
  workflow_dispatch:

jobs:
  add_submodule:
    runs-on: ubuntu-latest

    # Gewährt der Action die nötigen Schreibrechte im Repository
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Add Submodules
      run: |
        git config --global user.email "m.geerken@address-solutions.de"
        git config --global user.name "Michi71"
        
        # Submodule direkt in den Zielordner hinzufügen
        git submodule add -b master https://github.com/raspberrypi/pico-sdk.git lib/pico-sdk
        git submodule add -b master https://github.com/raspberrypi/pico-extras.git lib/pico-extras
         
        git submodule init
        git submodule update

    - name: Commit and Push changes
      run: |
        # Fügt die .gitmodules und die neuen Submodule-Ordner hinzu
        git add .gitmodules lib/
        
        # Verhindert Fehler, falls keine Änderungen vorhanden sind
        git diff-index --quiet HEAD || git commit -m 'Add pico-sdk, pico-extras submodules'
        
        git push
